### ISSUE TITLE
Requires directory to be in the home folder

### ISSUE THREAD

**Issue by syifan** [Multi2Sim/m2s-client-kit#4]

**Comment by amirkavyan** [comment]
I am not sure about this. I have it in another folder (Tools/m2s-client-kit/), and it still works. Is that the issue, or am I getting it wrong?

**Comment by syifan** [comment]
It does not work for me. When I run a command such as `./m2s-cluster.sh create abc`, I got an error `touch: cannot touch ‘/home/yifan/m2s-client-kit/tmp/m2s-cluster.ini’: No such file or directory`.

**Comment by amirkavyan** [comment]
Just was able to recreate it. I couldn't before, since I also had a m2s-client-kit repo (older version) in my home directory. 
@rafaelubal should we write a configure file to set the path to the m2s-client-kit in the scripts?

For example, the m2s_cluster_sh=$HOME/$M2S_CLUSTER_KIT_BIN/m2s_cluster.sh

This means if we don't have the m2s-cluster-kit in the home folder, the script cannot access the m2s_cluster.sh file. Should our configuration file change the $HOME (or a replacement variable -- i.e., $PATH) based on the current m2s-client-kit folder?

**Comment by rafaelubal** [comment]
Fixed
